---
title: "Exercice 1 -  module 1"
---  

* Dans la console, créer deux variables numériques a et b de valeur 5 et 4 par assignation : `a <- 5` et `b <- 4`  
* Que se passe-t-il dans le panneau Environnement (en haut à droite) ?  
* Faites maintenant un calcul avec ces variables comme `a+b` et `a*b`.  
* Vous allez ensuite créer une troisième variable à partir d'un calcul sur les deux premières : `c <- a + 3 * b`  
* Vous pouvez afficher la liste des variables avec la fonction `ls()`.  
* Modifiez maintenant la valeur de `a` en lui donnant la valeur 10. Vérifiez votre ré-assignation dans la panneau Environement.  
* Créez une variable chaîne de caractère : `t <- 'texte'` (vous pouvez également utiliser les doubles quotes comme "texte" mais ne les mélangez pas).
* Concaténez (mettez bout à bout) `a` et `t` avec la fonction `paste(a, t)`. Que constatez-vous ?
* Pour plus de renseignements sur la fonction `paste()`, pensez à utiliser l'aide de R avec `help(paste)`.
* Créez maintenant les variables `A <- 15` et `B <- 12`. Que voyez-vous dans la panneau Environement ?
* Vous pouvez supprimer la variables A et B en utilisant la fonction `rm()` (utilisez l'aide de R pour avoir plus de renseignements sur la fonction `rm`).



Résultat attendu :   

```{r, message=FALSE, warning=FALSE}
a <- 5 
a
b <- 4
b
a + b     
a * b
c <- a + 3 * b
c
ls()
a <- 10
c
t <- 'texte'
t
paste(a, t)
help(paste)
A <- 15  
B <- 12
rm(A, B)

```

