# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, 8-bascule-exercices-m6]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-22.04 # repasser en ubuntu-22.04 quand le package {magick} sera compatible avec la version ImageMagick 7 + libmagick++‑7.q16‑dev délivré par la dernière version de ubuntu
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # deps 1 : packages système Linux - cache APT
      - name: Cache deps linux (deps 1)
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-   

      # deps 2 : packages système Linux - installation
      - name: Install linux libraries (deps 2)
        run: |
          sudo apt-get update
          sudo apt-get install -y $(cat apt-packages.txt)  
          
      # deps 3 : packages système Linux - Cache TinyTeX et cargo
      - name: Cache TinyTeX et cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.TinyTeX
            ~/.cargo
          key: ${{ runner.os }}-tex-cargo 
          restore-keys: |
            ${{ runner.os }}-tex-

      # deps 4 packages R - installation et cache 
      # Note : installation de magick depuis github, le temps que magick version CRAN soit compatible avec ubuntu 24.04 qui fournit ImageMagick 7
      # Note : installation de santoku temporaire, le temps que santoku retourne sur le CRAN 			
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            pkgdown
            remotes
            tinytex
            ropensci/magick     
            hughjonesd/santoku  
          needs: website	  

      # deps 5 packages système Linux autre qu'APT, installation 
      - name: Install gifski et tinytex (deps 4)
        run: |
          cargo install gifski
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH  # écrit le chemin ~/.cargo/bin dans la variable d’environnement PATH du runner.
          Rscript -e 'if(length(tinytex::tinytex_root(error = FALSE)) > 0) tinytex::install_tinytex()'
      
      # deps 6  installation Marianne
      - name: Install police Marianne (deps 5)
        run: |
          systemfonts::register_font(name = "Marianne extrabold", system.file("resources/fonts/marianne/truetype/Marianne-ExtraBold.ttf", package = "gouvdown.fonts")) 
          systemfonts::register_font(name = "Marianne", system.file("resources/fonts/marianne/truetype/Marianne-Regular.ttf", package = "gouvdown.fonts")) 
          systemfonts::register_font(name = "Marianne light", system.file("resources/fonts/marianne/truetype/Marianne-Light.ttf", package = "gouvdown.fonts")) 
          systemfonts::register_font(name = "Marianne bold", system.file("resources/fonts/marianne/truetype/Marianne-Bold.ttf", package = "gouvdown.fonts")) 
          gouvdown::check_fonts_in_r()
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .
        
      - name: Build site
        run: |
          pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
          cat("correction du bug d'affichage dans avec gganimate, cf https://github.com/r-lib/pkgdown/issues/2334")
          vignette_m5 <- readLines("docs/articles/m05_exercices_module_datavisualisation_R.html")
          vignette_m5_cor <- gsub("../docs/", "../", vignette_m5)
          writeLines(vignette_m5_cor, "docs/articles/m05_exercices_module_datavisualisation_R.html")
          cat("Mise du rmd du chap 5 dans l'artifact pour comprendre pourquoi le resultat attendu est NULL")
          file.copy("vignettes/m05_exercices_module_datavisualisation_R.Rmd", to = "docs/articles/vign_M5.Rmd")
          cat("rendu specifique pour le M6 R Markdown")
          rmarkdown::render_site(input = "inst/rstudio/templates/project/ressources/m6/corrections/")
          fs::dir_copy(path = "inst/rstudio/templates/project/ressources/m6/corrections/cheesedown", "docs/cheesedown")
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: true
          branch: gh-pages
          folder: docs
